//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chem4Word.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chem4Word.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AboutBodydown {
            get {
                object obj = ResourceManager.GetObject("AboutBodydown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AboutfloatRight {
            get {
                object obj = ResourceManager.GetObject("AboutfloatRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AboutTop {
            get {
                object obj = ResourceManager.GetObject("AboutTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddElectron {
            get {
                object obj = ResourceManager.GetObject("AddElectron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddHydrogenDot {
            get {
                object obj = ResourceManager.GetObject("AddHydrogenDot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddLabel {
            get {
                object obj = ResourceManager.GetObject("AddLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddProton {
            get {
                object obj = ResourceManager.GetObject("AddProton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Apply {
            get {
                object obj = ResourceManager.GetObject("Apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Apply1 {
            get {
                object obj = ResourceManager.GetObject("Apply1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry Add-in for Word.
        /// </summary>
        public static string CHEM_4_WORD_MESSAGE_BOX_TITLE {
            get {
                return ResourceManager.GetString("CHEM_4_WORD_MESSAGE_BOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #sketcher_button_open, #sketcher_button_save {
        ///	display:none;
        ///}
        ///.
        /// </summary>
        public static string Chem4Word_css {
            get {
                return ResourceManager.GetString("Chem4Word_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Converts from degrees to radians.
        ///Math.radians = function (degrees) {
        ///    return degrees * Math.PI / 180;
        ///};
        ///
        ///// Converts from radians to degrees.
        ///Math.degrees = function (radians) {
        ///    return radians * 180 / Math.PI;
        ///};
        ///
        ///function AddHydrogensToAtom(atoms, bonds, bondlength, atom) {
        ///    var atomIdx = atoms.length;
        ///    var bondIdx = bonds.length;
        ///    var i;
        ///    var j;
        ///    var jj;
        ///
        ///    var hToAdd = atom.getImplicitHydrogenCount();
        ///
        ///    if (hToAdd &gt; 0) {
        ///        var seperation = 90;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Chem4Word_js {
            get {
                return ResourceManager.GetString("Chem4Word_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChemDoodleWeb_601_zip {
            get {
                object obj = ResourceManager.GetObject("ChemDoodleWeb_601_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ChemDoodleWeb_701_zip {
            get {
                object obj = ResourceManager.GetObject("ChemDoodleWeb_701_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical/x-cml.
        /// </summary>
        public static string CML_MIME_TYPE {
            get {
                return ResourceManager.GetString("CML_MIME_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;2.0&quot; cml:dummy-for-xmlns=&quot;&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:sch=&quot;http://www.ascc.net/xml/schematron&quot; xmlns:iso=&quot;http://purl.oclc.org/dsdl/schematron&quot; xmlns:cml=&quot;http://www.xml-cml.org/schema&quot;&gt;
        ///
        ///  &lt;!--PHASES--&gt;
        ///
        ///
        ///  &lt;!--PROLOG--&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; omit-xml-declaration=&quot;no&quot; standalone=&quot;yes&quot; indent=&quot;yes&quot; xmlns:svrl=&quot;http://purl.oclc.org/dsdl/svrl&quot; /&gt;
        ///
        ///  &lt;!--KEYS- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cmllite {
            get {
                return ResourceManager.GetString("cmllite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.xml-cml.org/schema&quot; elementFormDefault=&quot;qualified&quot; xmlns=&quot;http://www.xml-cml.org/schema&quot; xmlns:h=&quot;http://www.w3.org/1999/xhtml&quot; id=&quot;cmlschema&quot;&gt;
        ///  &lt;xsd:simpleType id=&quot;st.actionOrderType&quot; name=&quot;actionOrderType&quot;&gt;
        ///    &lt;xsd:annotation&gt;
        ///      &lt;xsd:documentation&gt;
        ///        &lt;h:div class=&quot;summary&quot;&gt;
        ///          Describes whether child elements are sequential or parallel.
        ///        &lt;/h:div&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CMLSchema {
            get {
                return ResourceManager.GetString("CMLSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeClicked {
            get {
                object obj = ResourceManager.GetObject("DupeClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeLinkedBoldNumberClicked {
            get {
                object obj = ResourceManager.GetObject("DupeLinkedBoldNumberClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeLinkedBoldNumberMouseOver {
            get {
                object obj = ResourceManager.GetObject("DupeLinkedBoldNumberMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeLinkedBoldNumberPlain {
            get {
                object obj = ResourceManager.GetObject("DupeLinkedBoldNumberPlain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeLinkedClicked {
            get {
                object obj = ResourceManager.GetObject("DupeLinkedClicked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeLinkedMouseOver {
            get {
                object obj = ResourceManager.GetObject("DupeLinkedMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeLinkedPlain {
            get {
                object obj = ResourceManager.GetObject("DupeLinkedPlain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupeMouseOver {
            get {
                object obj = ResourceManager.GetObject("DupeMouseOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DupePlain {
            get {
                object obj = ResourceManager.GetObject("DupePlain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Duplicate_Button {
            get {
                object obj = ResourceManager.GetObject("Duplicate_Button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EmptyTextBoxBackground {
            get {
                object obj = ResourceManager.GetObject("EmptyTextBoxBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipAboutBond {
            get {
                object obj = ResourceManager.GetObject("FlipAboutBond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipHorizontal {
            get {
                object obj = ResourceManager.GetObject("FlipHorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FlipVertical {
            get {
                object obj = ResourceManager.GetObject("FlipVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;!-- Add Mark Of The Web --&gt;
        ///    &lt;!-- saved from url=(0014)about:internet --&gt;
        ///
        ///	&lt;!-- Make .Net WebBrowser component work --&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot; /&gt;
        ///	
        ///    &lt;!-- http://hub.chemdoodle.com/cwc/latest --&gt;
        ///    &lt;!-- http://hub.chemdoodle.com/cwc/5.2.3 --&gt;
        ///
        ///    &lt;!-- these four are required by the ChemDoodle Web Components library --&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;chrome=1&quot; /&gt;
        ///	&lt;link rel=&quot;stylesheet&quot; href=&quot;http://hub.chem [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotLink_V523_html {
            get {
                return ResourceManager.GetString("HotLink_V523_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;!-- Add Mark Of The Web --&gt;
        ///    &lt;!-- saved from url=(0014)about:internet --&gt;
        ///
        ///	&lt;!-- Make .Net WebBrowser component work --&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot; /&gt;
        ///	
        ///    &lt;!-- http://hub.chemdoodle.com/cwc/latest --&gt;
        ///    &lt;!-- http://hub.chemdoodle.com/cwc/6.0.0 --&gt;
        ///
        ///    &lt;!--these three are required by the ChemDoodle Web Components library--&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;chrome=1&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;http://hub.c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotLink_V600_html {
            get {
                return ResourceManager.GetString("HotLink_V600_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Minus {
            get {
                object obj = ResourceManager.GetObject("Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;!-- Add Mark Of The Web --&gt;
        ///    &lt;!-- saved from url=(0014)about:internet --&gt;
        ///
        ///	&lt;!-- Make .Net WebBrowser component work --&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=9&quot; /&gt;
        ///	
        ///    &lt;!--these three are required by the ChemDoodle Web Components library--&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;chrome=1&quot;&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;ChemDoodleWeb/ChemDoodleWeb.css&quot; type=&quot;text/css&quot;&gt;
        ///    &lt;script type=&quot;text/javascript&quot; src=&quot;ChemDoodleWeb/ChemDoodle [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Offline_html {
            get {
                return ResourceManager.GetString("Offline_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://opsin-test.cloudapp.net/opsin/.
        /// </summary>
        public static string OPSIN_URL {
            get {
                return ResourceManager.GetString("OPSIN_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://opsin.ch.cam.ac.uk/opsin/.
        /// </summary>
        public static string OPSIN_URL_CAMB {
            get {
                return ResourceManager.GetString("OPSIN_URL_CAMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Plus {
            get {
                object obj = ResourceManager.GetObject("Plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;1.0&quot; xmlns:pc=&quot;http://www.ncbi.nlm.nih.gov&quot; xmlns:cml=&quot;http://www.xml-cml.org/schema&quot;&gt;
        ///
        ///  &lt;xsl:variable name=&quot;compound&quot; select=&quot;/pc:PC-Compounds/pc:PC-Compound&quot; /&gt;
        ///  &lt;xsl:variable name=&quot;id&quot; select=&quot;$compound/pc:PC-Compound_id&quot; /&gt;
        ///  &lt;xsl:variable name=&quot;compoundAtoms&quot; select=&quot;$compound/pc:PC-Compound_atoms&quot; /&gt;
        ///  &lt;xsl:variable name=&quot;bonds&quot; select=&quot;$compound/pc:PC-Compound_bonds&quot; /&gt;
        ///  &lt;xsl:v [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pubchem2cml {
            get {
                return ResourceManager.GetString("pubchem2cml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveElectron {
            get {
                object obj = ResourceManager.GetObject("RemoveElectron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveHydrogenDot {
            get {
                object obj = ResourceManager.GetObject("RemoveHydrogenDot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveIsotope {
            get {
                object obj = ResourceManager.GetObject("RemoveIsotope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveLabel {
            get {
                object obj = ResourceManager.GetObject("RemoveLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RemoveProton {
            get {
                object obj = ResourceManager.GetObject("RemoveProton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rotate {
            get {
                object obj = ResourceManager.GetObject("Rotate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SetCharge {
            get {
                object obj = ResourceManager.GetObject("SetCharge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shortcut {
            get {
                object obj = ResourceManager.GetObject("Shortcut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TextBoxBackground {
            get {
                object obj = ResourceManager.GetObject("TextBoxBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D.
        /// </summary>
        public static string TWO_D_LABEL {
            get {
                return ResourceManager.GetString("TWO_D_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Unlink {
            get {
                object obj = ResourceManager.GetObject("Unlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UnsetCharge {
            get {
                object obj = ResourceManager.GetObject("UnsetCharge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
