//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomInstaller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomInstaller.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chem4Word.AddIn.dll.
        /// </summary>
        internal static string ADD_IN_DLL_NAME {
            get {
                return ResourceManager.GetString("ADD_IN_DLL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Office\Word\Addins\Chemistry Add-in for Word.
        /// </summary>
        internal static string ADD_IN_REG_KEY {
            get {
                return ResourceManager.GetString("ADD_IN_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addins.
        /// </summary>
        internal static string ADDIN_REG_KEY {
            get {
                return ResourceManager.GetString("ADDIN_REG_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry Add-in for Word for Word 2007 and 2010.
        /// </summary>
        internal static string ADDINDESCRIPTION {
            get {
                return ResourceManager.GetString("ADDINDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry Add-in for Word.
        /// </summary>
        internal static string ADDINNAME {
            get {
                return ResourceManager.GetString("ADDINNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry Add-in for Word.
        /// </summary>
        internal static string ADDINTITLE {
            get {
                return ResourceManager.GetString("ADDINTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string BEFOREINSTALLMSG {
            get {
                return ResourceManager.GetString("BEFOREINSTALLMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling.
        /// </summary>
        internal static string BEFOREUNINSTALLMSG {
            get {
                return ResourceManager.GetString("BEFOREUNINSTALLMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check machine type (64 or 32 bit).
        /// </summary>
        internal static string CHECKMACHINETYPERROR {
            get {
                return ResourceManager.GetString("CHECKMACHINETYPERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Application Data\Chemistry Add-in for Word.
        /// </summary>
        internal static string CHEMISTRY_ADDIN_FOLDER_PATH_NONVISTA {
            get {
                return ResourceManager.GetString("CHEMISTRY_ADDIN_FOLDER_PATH_NONVISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \AppData\Local\Chemistry Add-in for Word.
        /// </summary>
        internal static string CHEMISTRY_WORD_ADDIN_FOLDER_PATH_VISTA {
            get {
                return ResourceManager.GetString("CHEMISTRY_WORD_ADDIN_FOLDER_PATH_VISTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chem4Word.AddIn.vsto.
        /// </summary>
        internal static string ChemistryWordAddInManifest {
            get {
                return ResourceManager.GetString("ChemistryWordAddInManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following applications should be closed before continuing the install:.
        /// </summary>
        internal static string CLOSE_APPLICATIONS_DURING_INSTALL {
            get {
                return ResourceManager.GetString("CLOSE_APPLICATIONS_DURING_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following applications should be closed before continuing the un-install:.
        /// </summary>
        internal static string CLOSE_APPLICATIONS_DURING_UNINSTALL {
            get {
                return ResourceManager.GetString("CLOSE_APPLICATIONS_DURING_UNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete settings file from all user’s profile.
        /// </summary>
        internal static string DELSETTINGFORALLERR {
            get {
                return ResourceManager.GetString("DELSETTINGFORALLERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESCRIPTIONSTRING {
            get {
                return ResourceManager.GetString("DESCRIPTIONSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :\Documents and Settings\.
        /// </summary>
        internal static string DOCUMENTS_AND_SETTINGS {
            get {
                return ResourceManager.GetString("DOCUMENTS_AND_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while checking live Word and InfoPath applications instances..
        /// </summary>
        internal static string ERRORAPPLICATIONOPEN {
            get {
                return ResourceManager.GetString("ERRORAPPLICATIONOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while preparing for installation..
        /// </summary>
        internal static string ERRORBEFOREINSTALL {
            get {
                return ResourceManager.GetString("ERRORBEFOREINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while preparing for un-installation..
        /// </summary>
        internal static string ERRORBEFOREUNINSTALL {
            get {
                return ResourceManager.GetString("ERRORBEFOREUNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while committing changes to the system..
        /// </summary>
        internal static string ERRORCOMMIT {
            get {
                return ResourceManager.GetString("ERRORCOMMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while installing Chemistry Add-in for Word for Word..
        /// </summary>
        internal static string ERRORINSTALL {
            get {
                return ResourceManager.GetString("ERRORINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while un-installing Chemistry Add-in for Word..
        /// </summary>
        internal static string ERRORUNINSTALL {
            get {
                return ResourceManager.GetString("ERRORUNINSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string EX_CATEGORY {
            get {
                return ResourceManager.GetString("EX_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        internal static string EX_INFORMATION {
            get {
                return ResourceManager.GetString("EX_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message:.
        /// </summary>
        internal static string EX_MESSAGE {
            get {
                return ResourceManager.GetString("EX_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string EX_STACKTRACE {
            get {
                return ResourceManager.GetString("EX_STACKTRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type:.
        /// </summary>
        internal static string EX_TYPE {
            get {
                return ResourceManager.GetString("EX_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FriendlyName.
        /// </summary>
        internal static string FRIENDLYNAME {
            get {
                return ResourceManager.GetString("FRIENDLYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get type of operating system.
        /// </summary>
        internal static string GETOSNAMEERR {
            get {
                return ResourceManager.GetString("GETOSNAMEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadBehavior.
        /// </summary>
        internal static string LOADBEHAVIORSTRING {
            get {
                return ResourceManager.GetString("LOADBEHAVIORSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest.
        /// </summary>
        internal static string Manifest {
            get {
                return ResourceManager.GetString("Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry Add-in for Word.
        /// </summary>
        internal static string MESSAGEBOXCAPTION {
            get {
                return ResourceManager.GetString("MESSAGEBOXCAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PATH {
            get {
                return ResourceManager.GetString("PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while working with registry.
        /// </summary>
        internal static string REGISTRYERROR {
            get {
                return ResourceManager.GetString("REGISTRYERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry Add-in for Word.
        /// </summary>
        internal static string REGKEYNAME {
            get {
                return ResourceManager.GetString("REGKEYNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while  removing settings file.
        /// </summary>
        internal static string REMOVESETTINGFILEERR {
            get {
                return ResourceManager.GetString("REMOVESETTINGFILEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \.
        /// </summary>
        internal static string SLASH {
            get {
                return ResourceManager.GetString("SLASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UNINSTALLACTION {
            get {
                return ResourceManager.GetString("UNINSTALLACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :\Users\.
        /// </summary>
        internal static string USERS_PATH {
            get {
                return ResourceManager.GetString("USERS_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vista.
        /// </summary>
        internal static string VISTA_OS_NAME {
            get {
                return ResourceManager.GetString("VISTA_OS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vstolocal.
        /// </summary>
        internal static string VSTOLocal {
            get {
                return ResourceManager.GetString("VSTOLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WINWORD.
        /// </summary>
        internal static string WINWORD {
            get {
                return ResourceManager.GetString("WINWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office Word.
        /// </summary>
        internal static string WORD_APPLICATION_TITLE {
            get {
                return ResourceManager.GetString("WORD_APPLICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string WORD_REGISTRY_KEY {
            get {
                return ResourceManager.GetString("WORD_REGISTRY_KEY", resourceCulture);
            }
        }
    }
}
