//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Numbo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Numbo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;cml:cml xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; id=&apos;aa&apos;&gt;
        ///  &lt;cml:cml convention=&apos;cmlDict:cmllite&apos; 
        ///    xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; 
        ///    xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; 
        ///    xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///    &lt;cml:molecule id=&apos;m1&apos; formalCharge=&apos;0&apos; spinMultiplicity=&apos;1&apos;&gt;
        ///      &lt;cml:name dictRef=&apos;nameDict:systematic&apos;&gt;alanine&lt;/cml:name&gt;
        ///      &lt;cml:formula concise=&apos;C 3 H 5 N 1 O 1 R 2&apos; /&gt;
        ///      &lt;cml:atomArray&gt;
        ///        &lt;cml:atom id=&apos;a5&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aminoacids {
            get {
                return ResourceManager.GetString("aminoacids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml xmlns=&apos;http://www.xml-cml.org/schema&apos; id=&apos;ane&apos;  xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///  &lt;cml convention=&apos;cmlDict:cmllite&apos;  &gt;
        ///    &lt;molecule id=&apos;m1&apos;&gt;
        ///      &lt;name dictRef=&apos;nameDict:systematic&apos;&gt;cyclohexano&lt;/name&gt;
        ///      &lt;name dictRef=&apos;nameDict:abbreviation&apos;&gt;chexo&lt;/name&gt;
        ///      &lt;formula concise=&apos;C 4 H 4 R 2&apos; inline=&apos;R1RCCCC1&apos;/&gt;
        ///      &lt;atomArray&gt;
        ///        &lt;atom i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ane {
            get {
                return ResourceManager.GetString("ane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml:cml id=&apos;Cu&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; 
        ///    xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; 
        ///    xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///&lt;cml:cml convention=&apos;cmlDict:cmllite&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///  &lt;cml:molecule id=&apos;m1&apos; formalCharge=&apos;2&apos;&gt;
        ///    &lt;cml:name dic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string copper {
            get {
                return ResourceManager.GetString("copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml:cml id=&apos;DIVALENT_SINGLE&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; 
        ///    xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; 
        ///    xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///&lt;cml:cml convention=&apos;cmlDict:cmllite&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///  &lt;cml:molecule id=&apos;m1&apos;&gt;
        ///    &lt;cml:name dictRef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string divalent {
            get {
                return ResourceManager.GetString("divalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml xmlns=&apos;http://www.xml-cml.org/schema&apos; id=&apos;ene&apos;  xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///  &lt;cml convention=&apos;cmlDict:cmllite&apos;  &gt;
        ///    &lt;molecule id=&apos;m1&apos;&gt;
        ///      &lt;name dictRef=&apos;nameDict:systematic&apos;&gt;benzo&lt;/name&gt;
        ///      &lt;name dictRef=&apos;nameDict:abbreviation&apos;&gt;benzo&lt;/name&gt;
        ///      &lt;formula concise=&apos;C 4 H 4 R 2&apos; inline=&apos;R1=RC=CC=C1&apos;/&gt;
        ///      &lt;atomArray&gt;
        ///        &lt;atom id=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ene {
            get {
                return ResourceManager.GetString("ene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml:cml id=&apos;R&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; 
        ///    xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; 
        ///    xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///&lt;cml:cml convention=&apos;cmlDict:cmllite&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///  &lt;cml:molecule id=&apos;m1&apos;&gt;
        ///    &lt;cml:name dictRef=&apos;nameDict:sys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string isolatedR {
            get {
                return ResourceManager.GetString("isolatedR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml xmlns=&apos;http://www.xml-cml.org/schema&apos; id=&apos;ketone&apos;  xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///  &lt;cml convention=&apos;cmlDict:cmllite&apos;&gt;
        ///    &lt;molecule id=&apos;m1&apos;&gt;
        ///      &lt;name dictRef=&apos;nameDict:systematic&apos;&gt;ol&lt;/name&gt;
        ///      &lt;name dictRef=&apos;nameDict:abbreviation&apos;&gt;CH(OH)&lt;/name&gt;
        ///      &lt;formula concise=&apos;C 2 H 3 O 2 R 1&apos; inline=&apos;C(O)&apos;/&gt;
        ///      &lt;atomArray&gt;
        ///        &lt;atom id=&apos;a1&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ketone {
            get {
                return ResourceManager.GetString("ketone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- note that the ID is used in dictionaries so DO NOT EDIT--&gt;
        ///&lt;cml xmlns=&apos;http://www.xml-cml.org/schema&apos; id=&apos;MONOVALENT_SINGLE&apos;&gt;
        ///	&lt;cml&gt;
        ///	&lt;molecule id=&apos;m1&apos;&gt;
        ///	    &lt;name dictRef=&apos;nameDict:systematic&apos;&gt;phenyl&lt;/name&gt;
        ///	    &lt;name dictRef=&apos;nameDict:abbreviation&apos;&gt;Ph&lt;/name&gt;
        ///	    &lt;formula concise=&apos;C 6 H 5 R 1&apos; inline=&apos;C6H5-&apos;/&gt;
        ///	    &lt;atomArray&gt;
        ///		&lt;atom id=&apos;a1&apos; elementType=&apos;C&apos; x2=&apos;1.8666666746139526&apos; y2=&apos;-0.5483672065041283&apos; /&gt;
        ///		&lt;atom id=&apos;a2&apos; elementType=&apos;C&apos; x2=&apos;3.200336015662211&apos; y2=&apos;1.761683615172993&apos; /&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monovalent {
            get {
                return ResourceManager.GetString("monovalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;cml:cml xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; id=&apos;o&apos;&gt;
        ///  &lt;cml:cml convention=&apos;cmlDict:cmllite&apos; xmlns:cml=&apos;http://www.xml-cml.org/schema&apos; xmlns:cmlDict=&apos;http://www.xml-cml.org/dictionary/cml/&apos; xmlns:nameDict=&apos;http://www.xml-cml.org/dictionary/cml/name/&apos;&gt;
        ///    &lt;cml:molecule id=&apos;m1&apos; formalCharge=&apos;0&apos; spinMultiplicity=&apos;1&apos;&gt;
        ///      &lt;cml:name dictRef=&apos;nameDict:systematic&apos;&gt;vinylalcohol&lt;/cml:name&gt;
        ///      &lt;cml:formula concise=&apos;C 2 H 3 Cl 1 R 2&apos; /&gt;
        ///      &lt;cml:atomArray&gt;
        ///        &lt;cml:atom i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string olefins {
            get {
                return ResourceManager.GetString("olefins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactor tests to normalize molecules
        ///Normalize after every significant operation
        ///validate after every significant operation
        ///cmlx:forced
        ///cmlx:nonchemistry max/min coord electron count charge forced
        ///==R (ylidene substituents)
        ///.
        /// </summary>
        internal static string TODO {
            get {
                return ResourceManager.GetString("TODO", resourceCulture);
            }
        }
    }
}
